/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "jett",
  "description": "大狗熊",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/a.webp",
        "heroText": 1991,
        "bgImage": "/e.jpg",
        "bgImageStyle": {
          "height": "540px",
          "boxShadow": "0 15px 18px rgba(0,0,0,0.2)"
        },
        "heroImageStyle": {
          "maxHeight": "288px",
          "display": "block",
          "borderRadius": "20% 81% 23% 77% / 44% 57% 43% 56%",
          "boxShadow": "0 15px 18px rgba(0,0,0,0.2)"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-c001c100",
      "path": "/"
    },
    {
      "title": "后端",
      "frontmatter": {
        "title": "后端",
        "date": "2023-1-1",
        "categories": [
          66
        ],
        "tags": [
          "JavaScript",
          "手写"
        ],
        "sticky": 2
      },
      "regularPath": "/blogs/2.html",
      "relativePath": "blogs/2.md",
      "key": "v-24f1e30e",
      "path": "/blogs/2.html"
    },
    {
      "title": "前端",
      "frontmatter": {
        "title": "前端",
        "date": "2023-1-1",
        "categories": [
          "前端"
        ],
        "tags": [
          "JavaScript",
          "手写"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/1.html",
      "relativePath": "blogs/1.md",
      "key": "v-5ad9a724",
      "path": "/blogs/1.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JavaScript Tags"
      },
      "regularPath": "/tag/JavaScript/",
      "key": "v-7a5f6990",
      "path": "/tag/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "手写 Tags"
      },
      "regularPath": "/tag/%E6%89%8B%E5%86%99/",
      "key": "v-de8294a6",
      "path": "/tag/手写/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "66 Categories"
      },
      "regularPath": "/categories/66/",
      "key": "v-35a4e791",
      "path": "/categories/66/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    }
  ],
  "themeConfig": {
    "subSidebar": "auto",
    "logo": "/b.png",
    "authorAvatar": "/b.png",
    "type": "blog",
    "author": "jti",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "我的博客",
        "items": [
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/233526039432445"
          },
          {
            "text": "Github",
            "link": "https://github.com/Xusssyyy"
          }
        ]
      }
    ],
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "博客"
      },
      "tag": {
        "location": 4,
        "text": "Tag"
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}