/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-24f1e30e",
        "v-5ad9a724"
      ]
    },
    "手写": {
      "key": "手写",
      "scope": "tags",
      "path": "/tag/手写/",
      "pageKeys": [
        "v-24f1e30e",
        "v-5ad9a724"
      ]
    }
  },
  "categories": {
    "66": {
      "key": 66,
      "scope": "categories",
      "path": "/categories/66/",
      "pageKeys": [
        "v-24f1e30e"
      ]
    },
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-5ad9a724"
      ]
    }
  },
  "timeline": {}
}